export interface HealthPackage {
  id: string;
  name: string;
  tagline: string;
  description: string;
  actualPrice: number;
  price: number; // 25% discounted offer price
  discountPercent: number;
  popular?: boolean;
  badge?: string;
  testsCount: number;
  tests: string[];
  fasting: string;
  sampleType: string;
  reportDelivery: string;
  recommendedFor: string;
}

export const healthPackages: HealthPackage[] = [
  {
    id: "whole-body-checkup",
    name: "Whole Body Checkup",
    tagline: "Total comprehensive full-body evaluation & vital organ profiling",
    description: "The most comprehensive screening covering blood profile, vital organs (liver, kidney, thyroid, heart), 2D Echo, Ultrasound, Vitamin D, and Vitamin B12.",
    actualPrice: 9700,
    price: 7760,
    discountPercent: 25,
    popular: true,
    badge: "25% OFF · Complete Screening",
    testsCount: 20,
    tests: [
      "Complete Blood Picture (CBP / CBC)",
      "Fasting Blood Sugar (FBS)",
      "Post Lunch Blood Sugar (PLBS)",
      "Glycosylated Hemoglobin (HbA1c)",
      "Lipid Profile (Cholesterol, HDL, LDL, Triglycerides)",
      "Liver Function Test (LFT)",
      "Serum Creatinine",
      "Blood Urea & Uric Acid",
      "Complete Urine Examination (CUE)",
      "HIV & HBsAg",
      "ECG (12-Lead Electrocardiogram)",
      "USG Whole Abdomen (Ultrasound)",
      "Serum Electrolytes (Sodium, Potassium, Chloride)",
      "2D Echo (Cardiac Echo Examination)",
      "25 Hydroxy Vitamin D",
      "Chest X-Ray PA View",
      "Thyroid Profile (T3, T4, TSH)",
      "Vitamin B12"
    ],
    fasting: "10-12 hours mandatory overnight fasting",
    sampleType: "Blood, Urine & Imaging (USG, X-Ray, 2D Echo, ECG)",
    reportDelivery: "Same Day Evening",
    recommendedFor: "Men & Women aged 30+ for annual complete vital health screening"
  },
  {
    id: "master-health",
    name: "Master Health Checkup",
    tagline: "Extensive pathology & imaging package for vital organs",
    description: "Master screening covering complete blood, diabetic average, lipid, kidney, liver, electrolytes, calcium, ECG, X-Ray, and Abdomen Ultrasound.",
    actualPrice: 5900,
    price: 4720,
    discountPercent: 25,
    popular: true,
    badge: "25% OFF · Most Popular",
    testsCount: 16,
    tests: [
      "Complete Blood Picture (CBP)",
      "Fasting Blood Sugar (FBS)",
      "Post Lunch Blood Sugar (PLBS)",
      "Complete Urine Examination (CUE)",
      "Lipid Profile",
      "Serum Creatinine",
      "Uric Acid & Blood Urea",
      "Liver Function Test (LFT)",
      "Thyroid Profile",
      "ECG (Electrocardiogram)",
      "Chest X-Ray PA View",
      "USG Abdomen (Ultrasound)",
      "Serum Electrolytes",
      "Serum Calcium",
      "HbA1c (Glycosylated Hemoglobin)"
    ],
    fasting: "10-12 hours overnight fasting",
    sampleType: "Blood & Urine + Diagnostic Imaging",
    reportDelivery: "Same Day",
    recommendedFor: "Executives, professionals, and adults for comprehensive preventative health"
  },
  {
    id: "executive-health",
    name: "Executive Health Checkup",
    tagline: "Targeted executive health assessment with infectious disease screening",
    description: "Specialized for corporate executives and active adults, including full metabolic screen, viral markers (HIV, HBsAg, HCV, VDRL), USG Abdomen & Pelvis, and Chest X-Ray.",
    actualPrice: 6200,
    price: 4960,
    discountPercent: 25,
    popular: false,
    badge: "25% OFF",
    testsCount: 17,
    tests: [
      "Complete Blood Picture",
      "Fasting Blood Sugar & PLBS",
      "Lipid Profile",
      "Serum Electrolytes",
      "Blood Urea & Uric Acid",
      "Serum Creatinine",
      "Liver Function Test (LFT)",
      "Thyroid Profile",
      "HIV & HBsAg",
      "HCV & VDRL",
      "ECG",
      "Chest X-Ray PA View",
      "Complete Urine Examination",
      "USG Abdomen & Pelvis"
    ],
    fasting: "10-12 hours fasting required",
    sampleType: "Blood, Urine & Imaging",
    reportDelivery: "Same Day",
    recommendedFor: "Corporate leaders, frequent travelers, and adults seeking thorough screening"
  },
  {
    id: "senior-citizen",
    name: "Senior Citizen Health Checkup",
    tagline: "Tailored geriatric health care with cardiac 2D Echo & PSA",
    description: "Designed specifically for seniors (aged 55+), covering inflammatory markers (ESR, CRP), diabetic control (HbA1c), cardiac echo, prostate (PSA for males), and bone health (Vitamin D).",
    actualPrice: 7900,
    price: 6320,
    discountPercent: 25,
    popular: true,
    badge: "25% OFF · Senior Care",
    testsCount: 12,
    tests: [
      "Complete Blood Picture",
      "Blood for ESR",
      "Glycosylated Hemoglobin (HbA1c)",
      "C-Reactive Protein (CRP)",
      "Liver Function Test (LFT)",
      "Chest X-Ray PA View",
      "Thyroid Profile",
      "25 Hydroxy Vitamin D",
      "ECG",
      "PSA (for Male Prostate Health)",
      "USG Abdomen",
      "2D Echo"
    ],
    fasting: "10-12 hours overnight fasting",
    sampleType: "Blood, Urine & Cardiac / Ultrasound Imaging",
    reportDelivery: "Same Day",
    recommendedFor: "Senior citizens (55+ years) for chronic disease and heart-joint monitoring"
  },
  {
    id: "well-women",
    name: "Well Women Checkup",
    tagline: "Specialized preventive screening for women's reproductive & metabolic health",
    description: "Essential wellness screen for women, focusing on blood counts, thyroid balance, kidney-liver function, lipid profile, and ultrasound abdomen/breast.",
    actualPrice: 4250,
    price: 3400,
    discountPercent: 25,
    popular: true,
    badge: "25% OFF · Women's Special",
    testsCount: 8,
    tests: [
      "Complete Blood Picture",
      "Fasting Blood Sugar",
      "Post Lunch Blood Sugar",
      "Blood Urea & Serum Creatinine",
      "Lipid Profile",
      "Thyroid Profile",
      "USG Abdomen / Breast"
    ],
    fasting: "8-10 hours fasting required",
    sampleType: "Blood, Urine & Ultrasound",
    reportDelivery: "Within 4 to 6 hours",
    recommendedFor: "Women of all age groups for annual hormone and abdominal screening"
  },
  {
    id: "well-men",
    name: "Well Men Checkup",
    tagline: "Dedicated men's health, prostate, bone, and cardiovascular profile",
    description: "Targeted men's health package including PSA prostate evaluation, Vitamin D, Chest X-Ray, ECG, Abdomen Ultrasound, and metabolic profiles.",
    actualPrice: 5500,
    price: 4400,
    discountPercent: 25,
    popular: false,
    badge: "25% OFF",
    testsCount: 14,
    tests: [
      "Complete Blood Picture",
      "Fasting Blood Sugar",
      "Post Lunch Blood Sugar",
      "Lipid Profile",
      "Serum Creatinine & Blood Urea",
      "Uric Acid",
      "Thyroid Profile",
      "25 Hydroxy Vitamin D",
      "Complete Urine Examination",
      "ECG",
      "USG Abdomen & Pelvis",
      "Chest X-Ray PA View",
      "PSA Total (Prostate Specific Antigen)"
    ],
    fasting: "10-12 hours fasting required",
    sampleType: "Blood, Urine & Imaging",
    reportDelivery: "Same Day",
    recommendedFor: "Men aged 30+ for prostate, heart, and metabolic evaluation"
  },
  {
    id: "diabetic-care",
    name: "Diabetic Profile",
    tagline: "Complete glucose control, organ risk assessment & complication screening",
    description: "In-depth diabetic checkup assessing HbA1c (3-month blood sugar), renal function (RFT), liver function (LFT), urine ketone bodies, USG KUB (Kidneys & Bladder), and ECG.",
    actualPrice: 4200,
    price: 3360,
    discountPercent: 25,
    popular: true,
    badge: "25% OFF · Diabetic Focus",
    testsCount: 9,
    tests: [
      "Fasting Blood Sugar (FBS) & PLBS",
      "Lipid Profile",
      "HbA1c (Glycosylated Hemoglobin)",
      "Renal Function Test (RFT)",
      "Liver Function Test (LFT)",
      "Urine for Ketone Bodies",
      "USG KUB (Kidney, Ureter, Bladder)",
      "Complete Urine Examination (CUE)",
      "ECG"
    ],
    fasting: "8-10 hours fasting for morning sample",
    sampleType: "Blood, Urine & Ultrasound KUB",
    reportDelivery: "Same Day",
    recommendedFor: "Diabetic & pre-diabetic patients, hypertension, and metabolic syndrome"
  },
  {
    id: "antenatal-care",
    name: "Antenatal Profile",
    tagline: "Essential pregnancy blood & viral screening for mother & baby safety",
    description: "Complete routine maternal evaluation required during pregnancy, including blood group, bleeding & clotting times, viral markers (HIV, HBsAg, HCV, VDRL), and thyroid profile.",
    actualPrice: 3050,
    price: 2440,
    discountPercent: 25,
    popular: false,
    badge: "25% OFF · Maternity",
    testsCount: 12,
    tests: [
      "Complete Blood Picture (CBP)",
      "Blood Group & Rh Typing",
      "Bleeding Time & Clotting Time (BT / CT)",
      "Random Blood Sugar (RBS)",
      "HIV & HBsAg (Hepatitis B)",
      "VDRL & HCV",
      "Complete Urine Examination (CUE)",
      "Serum Creatinine & Serum Bilirubin",
      "Thyroid Profile"
    ],
    fasting: "No special fasting required",
    sampleType: "Blood & Urine",
    reportDelivery: "Within 4 hours",
    recommendedFor: "Expecting mothers for first-trimester and ongoing antenatal health check"
  },
  {
    id: "general-health",
    name: "General Health Checkup",
    tagline: "Affordable baseline vital checkup for everyday health monitoring",
    description: "Essential diagnostic baseline covering blood counts, ESR, fasting blood sugar, urine routine, kidney-liver markers, blood group, Abdomen USG, ECG, and Chest X-Ray.",
    actualPrice: 2900,
    price: 2320,
    discountPercent: 25,
    popular: false,
    badge: "25% OFF · Best Value",
    testsCount: 10,
    tests: [
      "Complete Blood Picture",
      "Erythrocyte Sedimentation Rate (ESR)",
      "Fasting Blood Sugar & PLBS",
      "Complete Urine Examination",
      "Serum Bilirubin & Serum Creatinine",
      "Blood Grouping",
      "USG Abdomen & Pelvis",
      "ECG",
      "Chest X-Ray PA View"
    ],
    fasting: "8-10 hours fasting required",
    sampleType: "Blood, Urine & Imaging",
    reportDelivery: "Same Day",
    recommendedFor: "Students, working professionals, and general routine checkups"
  },
  {
    id: "heart-care",
    name: "Heart Checkup",
    tagline: "Cardiovascular risk assessment with 2D Echo, TROP-T & Lipid Profile",
    description: "Focused cardiac evaluation including resting ECG, 2D Echocardiography, Troponin-T (cardiac injury marker), and full lipid profile for cholesterol assessment.",
    actualPrice: 3600,
    price: 2880,
    discountPercent: 25,
    popular: true,
    badge: "25% OFF · Cardiac Care",
    testsCount: 4,
    tests: [
      "ECG (12-Lead Electrocardiogram)",
      "2D Echo (Cardiac Ultrasound & Doppler)",
      "TROP-T (Troponin-T Test)",
      "Lipid Profile (Total Cholesterol, Triglycerides, HDL, LDL)"
    ],
    fasting: "10-12 hours overnight fasting for lipid accuracy",
    sampleType: "Blood & Cardiac Diagnostic Imaging",
    reportDelivery: "Same Day",
    recommendedFor: "Individuals with family history of cardiac issues, chest discomfort, or high cholesterol"
  }
];
